### ISSUE TITLE
8.2 Compatibility?

### ISSUE THREAD

**Issue by patriclougheed** [otetard/ownpad#1]
Any chance we can see an update to allow this to work with 8.2? I can get it to install but menus will not show.

Thanks for a great plugin!

**Comment by otetard** [comment]
I tried to port the existing code to 8.2. This version comes with a new menu which would require a lot of work in the ownpad plugin to be compatible with. Unfortunately, I don’t intend to support that version.

A way to extends this “New” menu was added to ownCloud 9 owncloud/core@d3861685045a006b47c68185223be21a6233802e (but won’t be backported to 8.2). To use ownpad in ownCloud 8.2, you’ll need to apply this patch and use the `features/port-to-owncloud9` branch of the ownpad plugin.

Cheers,
Olivier;

**Comment by patriclougheed** [comment]
Thanks! Just an FYI...

I was able to install the branch and patch without issue and menu items have appeared again but receive this message with any file name created for both etherpad and ethercalc:

"The name is already used in the folder /. Please choose a different name."

Also existing pad and calc shortcuts do not open, they just try to download.

**Comment by otetard** [comment]
Hi!

> I was able to install the branch and patch without issue and menu items have appeared again but receive this message with any file name created for both etherpad and ethercalc:
> 
> "The name is already used in the folder /. Please choose a different name."

Thanks, I forget to backport a tiny patch to the `feature/port-to-owncloud9`. BTW, I’ve merged this branch to the `master` one, you can now switch to it.

> Also existing pad and calc shortcuts do not open, they just try to download.

It’s probably an issue with the MIME type that is used in ownpad. You can use that command to update the MIME type associated to your existing files:

```
php occ files:scan
```

Olivier;
