### ISSUE TITLE
Nextcloud 21

### ISSUE THREAD

**Issue by sunjam** [otetard/ownpad#102]
Please add support.  Thanks!

**Comment by pierfu** [comment]
Hello,
thanks for this useful app.
Any plan to release version for NC20 or NC21 ?
At this moment it's the only app that prevents me from upgrading from NC19.

**Comment by real34** [comment]
My 2cts from a quick analysis.
Many errors seems to be related to direct usages of `\OC\Files\Filesystem`. I have no experience at all in NC development, so not sure about what is the now correct way to access the file system.
There seems to be a `$fileAccessHelper` dependency that can be injected, it may be a solution.

**Comment by otetard** [comment]
@pierfu @real34 I made a proposal to fix Nextcloud 21 compatibility in this PR: #104. Fix could be easily tested.

If everything works as expected I will push a new release of Ownpad.

**Comment by pierfu** [comment]
Great, but I cannot test that on my side with an NC21 instance.

**Comment by real34** [comment]
Hi!
Sorry for the delay… thanks for taking the time to fix it and do a release.

I confirm that v0.6.16 works fine on a NC21 instance!
