### ISSUE TITLE
Availability for Nextcloud 22

### ISSUE THREAD

**Issue by pierfu** [otetard/ownpad#107]
Hello,
thanks again Olivier ! Same as #102 : any plan to release version for NC22 ?
Only - but wanted ! - app preventing me from upgrading from NC21.

**Comment by guidtz** [comment]
Idem in Nextcloud 23 ?

Regards

**Comment by scriptFactors** [comment]
YES - very much waiting for NC22/23 compatibility.

salut,

**Comment by otetard** [comment]
0.6.17 release was pushed to Nextcloud’s App store. This version is compatible with NC 22 & NC 23 (without any changes on Ownpad code).

**Comment by scriptFactors** [comment]
GREAT! and THANKS!

**Comment by pierfu** [comment]
+1

**Comment by real34** [comment]
Thanks! I could install it on a 22.2.3 successfully.

I'd be interested in providing feedback, and even a PR to update the version if it works on a new version.
However I don't have any knowledge of NC development.
Could you provide some details about how I could _bypass_ NC's checks and try Ownpad with a new version?

**Comment by otetard** [comment]
> Could you provide some details about how I could bypass NC's checks and try Ownpad with a new version?

You can try [this solution](https://help.nextcloud.com/t/use-command-line-occ-to-install-incompatible-apps/120193/2). It should also be possible to allow installation of incompatible apps in the UI.
