### ISSUE TITLE
open pad from [Tags] / [Favorites] 

### ISSUE THREAD

**Issue by inos-github** [otetard/ownpad#11]
Environment:
Nextcloud 9.0.53
ownpad 0.52 / etherpad-api (https://github.com/otetard/ownpad/commit/290e5e40f184f71edcbb5a43dec35a99cf962280)

clicking on a pad link within the [tags] or [favorites] sub-page of the [files] app, the pad opens as a kind of "overlay" to the calling sub-page. As a result, the icons of the calling page are still visible after the pad has been loaded.

(see screenshot)
![image](https://cloud.githubusercontent.com/assets/6089198/18438901/88786c9c-7903-11e6-8ca4-2b3411dd8b96.png)

**Comment by blackisle51** [comment]
I can confirm this behaviour with Nextcloud 10.

**Comment by otetard** [comment]
Is this bug still present with the current Nextcloud version? If so, feel free to reopen that bug!

Olivier;
