### ISSUE TITLE
Website will not allow Firefox to display the page if another site has embedded it

### ISSUE THREAD

**Issue by manu-p** [otetard/ownpad#113]
Hi, 

NC (22.2.3) and Etherpad (1.8.7) are self hosted (Ubuntu server 20.04.3) and, using the ownpad app, we've been able for years now to open embedded pads within NC.
Lately, the self hosted mail systems on the same server have been updated to a new release. Since then, we get the following error:
- using FF: Website will not allow Firefox to display the page if another site has embedded it
- using Brave (or any chrome derivatives): pad._ourdomain_ does not allow connection. (n'autorise pas la connexion in french)

In both cases it is possible to open the pads, externally.

No changes in Etherpad settings.json, no changes in NC config file. 

The ownpad app conf shows: Etherpad Host: https://pad._oudomain_ as before. 

So far I did not find errors in logs, but maybe I've not been searching enough.

Any clue? Where should I search for information related to this issue?

**Comment by otetard** [comment]
This isn’t related to Ownpad itself.

It seems that this issue was fixed by updating NGINX’s configuration (`X-Frame-Options` HTTP header): https://help.nextcloud.com/t/solved-website-will-not-allow-firefox-to-display-the-page-if-another-site-has-embedded-it/133509
