### ISSUE TITLE
Styling of top bar (you all can use my CSS file)

### ISSUE THREAD

**Issue by fenglisch** [otetard/ownpad#116]
I really like this app, but the top bar is pretty ugly, breaking the design of my cloud. It's super easy to style by editing the `../apps/ownpad/css/ownpad.css`, but I don't know why it's not well-designed by default.

Anyway, I styled it so that it fits to the rest of the Etherpad. Feel free to use my CSS file. You can download it from here (https://nextcloud.wechange.de/s/GX6G8oteq7cxSff) together with the font files. Just upload the folder `/fonts` to `../apps/ownpad`
Before: 
![grafik](https://user-images.githubusercontent.com/61431524/173037260-5d977b10-5a9a-451f-846e-8fdaa9f24a28.png)

After:
![grafik](https://user-images.githubusercontent.com/61431524/173037678-1dfa2c65-2777-40e0-8d1f-b323c9f06f3b.png)

**Comment by otetard** [comment]
Thanks for this contribution! I will provide a new version shortly (hopefully :)).

**Comment by otetard** [comment]
This issue should be fixed in Ownpad 0.7.0. Thanks for the feedback!
