### ISSUE TITLE
New pad created in the root directory and not in the current one

### ISSUE THREAD

**Issue by otetard** [otetard/ownpad#120]
It can now be enabled on my instance, however I have a weird behavior when creating a new pad: it is created at the root directory for the current user.

Since it might be a Nextcloud 25 (or 0.7.0) only issue I mention it here. I haven't found any similar issues on the bugtracker yet.
Let me know if you prefer that I open a new one.

To reproduce: in a directory, create a new pad
What happens:
- opening the pad directly leads to a "the URL specified in your file does not match the allowed server." error
- the new pad disappears when refreshing the page
- we can find it (and open it successfully) in the top-level directory

Expected:
- the file should be created in the directory and remain there
- it could be opened from there

Demo:

https://user-images.githubusercontent.com/75968/201534708-0c93632e-35cb-4852-9be9-00741e14a0f4.mp4

_Originally posted by @real34 in https://github.com/otetard/ownpad/issues/119#issuecomment-1312779295_

**Comment by otetard** [comment]
I confirm this issue. This is due to some changes in the `files` app. I’ll try to fix this quickly.

**Comment by otetard** [comment]
Bug is now fixed in 0.7.1 (8e07b0d7fa78e1e708199cf9c9c0d986aa177ffd). Issue was due to a change in Nextcloud 25: https://github.com/nextcloud/server/pull/33373

**Comment by real34** [comment]
Thanks a lot!
I could install `0.7.1` and I confirm it fixes the issue.

So far, so good… everything seems to be working as expected!
:pray: :+1:
