### ISSUE TITLE
keep this module avalaible for Nextcloud versions 26.*

### ISSUE THREAD

**Issue by rodinux** [otetard/ownpad#122]
Hello,
thanks for this module very useful. Does it will be maintained in Nextcloud version 26 ? I have upgraded my instance to 26.0.2 and don't know if I could take the risk  to activate the module...

**Comment by rodinux** [comment]
Ok, I have take the risk to activate the module... so it works, nice !
Not all as excepted, when I open a file `.pad`, the window is not full screen, it is cut by the nextcloud navigation column of the directory. But if I click on `close the navigation` icon on the left top of the pad, it close the nextcloud navigation column, and I can see the pad... Very strange because I imagine this icon is here to close the navigation column of the pad, isn't it ?

**Comment by otetard** [comment]
I’ve just published a v0.8.0 version that add support for Nextcloud 25 to 28. This version also make use of the Files Viewer application to open “pad” files.

Please let me know if you encounter any issue with this new version!
