### ISSUE TITLE
Pad doesn't load since version 0.8.x on NC v25 without any errors

### ISSUE THREAD

**Issue by SimJoSt** [otetard/ownpad#127]
We just updated from 0.7.1 to 0.8.1 and now the pads are not loaded anymore. The files with right extensions are still recognized, the app is opening the app (now in the file viewer) but the content, the iframe is missing.
There is no error shown in the browser nor the developer console.

It worked fine before, not settings were changed and Etherpad is accessible directly.
What kind of tests and debugging information can we provide to help fix this?

**Comment by otetard** [comment]
Thanks for reporting that bug.

Can you share me a screenshot of what you see please? In the network tab of your dev tools console, can you see any call to `/apps/ownpad/?file=`? If so, what is the status of that call?

**Comment by SimJoSt** [comment]
@otetard we just updated to Nextcloud version 26.0.5 and it works again. So I cannot make a screenshot right now 🙈 
I updated the title of this issue, to specify the bug occurred with Nextcloud version 25.x.x

**Comment by SimJoSt** [comment]
The easiest solution might be to increase the min Nextcloud version for the > 0.8.x versions of the app.

**Comment by otetard** [comment]
I tried to reproduce this issue with Nextcloud 25 but I didn’t succeed :/.

**Comment by otetard** [comment]
Closing this issue. This one can be reopened if someone encounters this issue too.
