### ISSUE TITLE
add pad or private pad not in the menu add files since nextcloud 28.0.1 upgrade

### ISSUE THREAD

**Issue by rodinux** [otetard/ownpad#139]
I have updated to nextcloud 28.0.1, I can open the pads created in nextcloud, but in the menu, I can't see more add pad, private pad or ethercalc !

**Comment by rodinux** [comment]
If it could help, I put here last logs

```
{"reqId":"tRuaiJSiCLqLJeA9Pn2c","level":3,"time":"2024-01-14T00:25:25+00:00","remoteAddr":"2a0d:e487:14f:fcea::1","user":"technique","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"file_put_contents(/var/www/nextcloud/config/mimetypemapping.json): Failed to open stream: Permission denied at /var/www/nextcloud/apps/ownpad/lib/Migration/RegisterMimeType.php#85","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"sFjUCme9yyd3GrFL4yZh","level":3,"time":"2024-01-14T00:36:46+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_put_contents(/var/www/nextcloud/config/mimetypemapping.json): Failed to open stream: Permission denied at /var/www/nextcloud/apps/ownpad/lib/Migration/UnregisterMimeType.php#85","userAgent":"--","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"HbeEKa2t4KMwyWpzMA1B","level":3,"time":"2024-01-14T00:40:56+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_put_contents(/var/www/nextcloud/config/mimetypemapping.json): Failed to open stream: Permission denied at /var/www/nextcloud/apps/ownpad/lib/Migration/RegisterMimeType.php#85","userAgent":"--","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"HbeEKa2t4KMwyWpzMA1B","level":3,"time":"2024-01-14T00:40:56+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_put_contents(/var/www/nextcloud/config/mimetypemapping.json): Failed to open stream: Permission denied at /var/www/nextcloud/apps/ownpad/lib/Migration/RegisterMimeType.php#85","userAgent":"--","version":"28.0.1.1","data":{"app":"PHP"}
```

**Comment by Mottek57** [comment]
OwnPad not work since 28.0.
In 'Files (+New)'  there is no longer posible to create a new 'Pad' or 'Calc'-File...
Please, can you fix it?

**Comment by rodinux** [comment]
It need some refactoring, if I have understood, the code have changed with API 

https://docs.nextcloud.com/server/28/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#removed-apis

So not easy to do...

**Comment by otetard** [comment]
This issue should be fixed with Ownpad v0.10.0-beta.1.

Please let me know if you encounter any issue with this version so I can release the official stable release then.

**Comment by rodinux** [comment]
Hello, thanks ! so how I can test it ? I can upload the git source and put it on the folder `/var/www/nextcloud/apps/` ? or there is a procedure ?

**Comment by otetard** [comment]
> Hello, thanks ! so how I can test it ?

You can install it by changing the release channel of Nextcloud to ”beta”. You'll be proposed to update the app. Otherwise, you can download that version on https://apps.nextcloud.com/apps/ownpad

**Comment by rodinux** [comment]
Sorry, I see it is now on branch master, I just need wait to see the upgrade coming soon... Thanks

**Comment by rodinux** [comment]
well, the instance nextcloud is on a Yunohost, I can't change the release on it or don't find how to do... I have try also upload and then put it on the folder apps but nextcloud don't see it. 
Is it possible put the folder ownpad uploaded on apps directory and after how do something to do make the app been seen to try activate it ?? with occ ?

**Comment by rodinux** [comment]
Ok I found how to enable it, I will test it !

**Comment by rodinux** [comment]
So I can create Pads (public and private), but it seems to have a bug when trying to share a private pad... 
I try share with another user, in the column it seems ok, but in the line there is no icon share and the user don't see the share...

![Capture d’écran du 2024-01-26 00-12-33](https://github.com/otetard/ownpad/assets/11272759/1fa61675-fe75-4eaf-a271-15924d12845a)

![Capture d’écran du 2024-01-26 00-13-53](https://github.com/otetard/ownpad/assets/11272759/f97f8db5-d7e2-47ca-a3c6-c29aa41b8bf0)

**Comment by rodinux** [comment]
Perhaps it is because even if I have add my API key on the parameter, my settings.json for etherpad_mypads on Yunohost have these parameters

```
  "requireSession": false,
  "editOnly": false,
```

**Comment by rodinux** [comment]
Wait ! after `occ files:scan --all` and `occ files:scan-app-data` I see the share, the user also, it works like a charm !
Thank you so much

**Comment by otetard** [comment]
Thanks for the feedback! I’ve just pushed a stable v0.10.0 release that will be available in a few minutes on the Appstore.
