### ISSUE TITLE
ownpad causes "Problem reloading page in 5 seconds" on public share links

### ISSUE THREAD

**Issue by muppeth** [otetard/ownpad#14]
As the title says. Opening public links by non-logged in users causes nextcloud to reload shared link page every 5 seconds.

Running the page in debug mode in the browser I noticed it calls:
GET XHR https://mycloud.example.org/apps/ownpad/ajax/getconfig.php

Disabling ownpad app makes the problem go away.

**Comment by otetard** [comment]
This issue was fixed with this commit 1256ab18f5dbddf02c4f93cc520033b3a0d80932 (version 0.5.6) which was uploaded to the Nextcloud’s appstore but not yet to ownCloud’s one.

Olivier;

**Comment by muppeth** [comment]
Cool thanks for the info. I haven't switch to nextcloud appstore yet. 

On November 25, 2016 3:51:03 PM GMT+01:00, "Olivier Tétard" <notifications@github.com> wrote:
>This issue was fixed with this commit
>1256ab18f5dbddf02c4f93cc520033b3a0d80932 (version 0.5.6) which was
>uploaded to the Nextcloud’s appstore but not yet to ownCloud’s one.
>
>Olivier;
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/otetard/ownpad/issues/14#issuecomment-262971330

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
