### ISSUE TITLE
Ownpad on Docker Nextcloud

### ISSUE THREAD

**Issue by berzas** [otetard/ownpad#15]
Hi!

I'm using Nextcloud trough Docker via docker-compose. I'm using wonderfall/nextcloud repo adding some environment for connecting trough reverse Nginx proxy to serve the site with Let's Encrypt. On the same server we have Etherpad instance running also on Docker and with Let's Encrypt. Everything runs great. 

Now we would like to use Ownpad to integrate pads on Nextcloud. I configured everything adapting your instructions for Docker commands. Every command was fine without any errors even Mimetype detection instructions. But when we try to edit pads, instead of edit just opens the pop-up for download. 

¿How we could try to solve this, any ideas?

Thanks

**Comment by otetard** [comment]
Hi,

Sorry for the late answer. Do you encounter the same issue if you create new pads? Did you try to ask Nextcloud to rescan all the files?

    sudo -u www-data php occ files:scan --all

Olivier;

**Comment by dalareo** [comment]
I am using Wonderfall version of Nextcloud and still not able to make pad files been open by my Etherpad service. Only downloading available.
I've changed mimetypemappings.json before as set in instructions and then I execute:
```
docker exec -ti container_name occ files:scan --all
```
