### ISSUE TITLE
min-version

### ISSUE THREAD

**Issue by avoidik** [otetard/ownpad#2]
**ownpad/appinfo/info.xml**

is it correct that min-version is 9?

**Comment by otetard** [comment]
Hi,

Yes, ownpad is only compatible with ownCloud <= 8.1 (the `owncloud-8.1` branch) or with ownCloud > 9 (the `master` branch). The version on the `master` branch requires the “New” menu that [was added to ownCloud 9](owncloud/core@d3861685045a006b47c68185223be21a6233802e).

If you want to use ownpad, you can backport [this patch](owncloud/core@d3861685045a006b47c68185223be21a6233802e) to your 8.2 installation of ownCloud.

Olivier;
