### ISSUE TITLE
CSP blocks it…

### ISSUE THREAD

**Issue by rugk** [otetard/ownpad#21]
In NextCloud 11 the CSP includes `frame-src 'self';child-src 'self'`, which blocks frames from other hosts. So when using an Etherpad/calc instance from another host this renders the app unusable…

Maybe you could include the specific domain in the CSP…

**Comment by otetard** [comment]
I’ve just tested using Nextcloud 11 with an Etherpad instance hosted on another domain without any problem. Could you please post your CSP related console logs?

**Comment by rugk** [comment]
Actually it is not really shown in the console, but in the whole page:
![csp](https://cloud.githubusercontent.com/assets/11966684/24306310/7ac992b0-10c0-11e7-91a3-d2d8c15ad6ea.png)
Rough translation: Blocked by internet security policy (CSP))

That's the CSP: `default-src 'none';script-src 'nonce-Vnh0M25Pb2hFZ0d5QVVWeDY0Lzk0QVJTSGEr[…]WNYOD0=' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self';frame-src https://EXTERNAL_URL_TO_ETHERPAD/ https://EXTERNAL_URL_TO_ETHERCALC/`

**Comment by otetard** [comment]
Hi!

I’m sorry I can’t reproduce this issue. I’ve tested Ownpad with several configuration and browsers (Firefox, Firefox dev edition, Chromium) and I never faced this issue.

Could this be related to one of your Firefox plugin? I can see that you have a CSP warning which says something related to referrers policy which does not seems to be sent by Nextcloud itself (according to the CSP you pasted). By trying to reproduce this bug with Firefox dev edition, the “`frame-src`” is displayed, but not the two others.

Olivier;

**Comment by otetard** [comment]
I can’t reproduce the bug. Feel free to reopen it if this issue is still valid.

Olivier;
