### ISSUE TITLE
Mimetype not recognized

### ISSUE THREAD

**Issue by reneglauser** [otetard/ownpad#23]
Hi
I installed the ownpad app on Nextcloud 11 and followed your explanations concerning mimetypemapping.json but when I click on a file.pad document inside nextcloud, the file is always beeing downloaded. The pad does not open inside nextcloud.
What could be wrong?
regards
René

**Comment by unraun** [comment]
Solution is in the description under "Mimetype detection"

> Unfortunately, apps can’t declare new mimetypes on the fly. To make
> Ownpad work properly, you need to add two new mimetypes in the
> `mimetypemapping.json` file (at ownCloud level).
> 
> To proceed, just copy `/resources/config/mimetypemapping.dist.json` to
> `/config/mimetypemapping.json`, and then add the two following lines
> just after the “_comment” lines.
> 
>     "pad": ["application/x-ownpad"],
>     "calc": ["application/x-ownpad"],
> 
> If all other mimetypes are not working properly, just run the
> following command:
> 
>     sudo -u www-data php occ files:scan --all

**Comment by toby00001** [comment]
I'm having the same issue, file scan completed with no errors and ownership corrected for mimetypemapping.json - still my browser just downloads the .pad file every time rather than launching OwnPad.

**Comment by otetard** [comment]
Could you please copy you `mimetypemapping.json` so I can check its syntax please?

Olivier;

**Comment by reneglauser** [comment]
Here is my mimetypemapping.json

{
        "_comment" : "Array mapping file extensions to mimetypes (in alphabetical order]",
        "_comment2": "The first index in the mime type array is the assumed correct mimetype",
        "_comment3": "and the second (if present] is a secure alternative",

        "_comment4": "Any changes you make here will be overwritten on an update of Nextcloud",
        "_comment5": "Put any custom mappings in a new file mimetypemapping.json in the config/ folder of Nextcloud",


        "pad": ["application/x-ownpad"],
        "calc": ["application/x-ownpad"]
}

**Comment by otetard** [comment]
Thanks for the feedback. Was that file put in the `config/` folder of your Nextcloud/ownCloud, next to the `config.php` file?

You also should have lines before the “`calc`” one (or after, as you wish, but in this case you need to add a coma after the ”`calc`” line). You just need to add the two “`pad`”/”`calc`” lines just after the “`comments`” lines and keep the rest of the file intact.

Olivier;

**Comment by reneglauser** [comment]
Thanks for your comment. My file was placed at: /var/www/nextcloud/resources/config

So I moved it to: /var/www/nextcloud/config

Now it works.....thank you. So I did not exactly understand where to copy the file by ready the documentation....now its clear.
Thanks.

**Comment by otetard** [comment]
Perfect. I’ve just updated the `README.md` to be more explicit on where to put the file.

**Comment by reneglauser** [comment]
Thanks...now the manual is more clear.

Another question:
Is it possible to access pads from owncloud with the "apikey" of etherpad?

**Comment by otetard** [comment]
Not sure of what you’re talking about, but there’s a branch which allows usage of Etherpad API: https://github.com/otetard/ownpad/tree/feature/etherpad-api. By using the API you can create “private pads” which are only available to NC/OC users (if they have the right to access the file).

**Comment by reneglauser** [comment]
Yes I am thinking about private pads. So this feature seems to be still in development? Right?

**Comment by otetard** [comment]
The ability to create private pads is available and usable on that branch (which is not in sync with `master`), but it’s not feature complete (see [`TODO.md`](https://github.com/otetard/ownpad/blob/feature/etherpad-api/TODO.md)). I need to find some time to finish that work.

**Comment by reneglauser** [comment]
ok..thanks......
