### ISSUE TITLE
Not checking URLs

### ISSUE THREAD

**Issue by inhalte** [otetard/ownpad#24]
Discovered a security-issue, that the ".pad"-Files are not checked for their containing URLs.

Possible Attack:
1. Person creates Pad in shared folder.
2. Attacker opens ".pad" file and changes
`URL=https://good.url/p/SOMESTRING`
to
`URL=https://bad.url/p/YOUHAVEBEENHACKED`
3. Altered ".pad"-Files is synchronized with cloud of Person
4. Person opens Pad and will be forwarded to the bad.url

One solution could be to check the URL-variable for valid Server-URLs defined past and present in the settings.

Edit: See my pull-request

**Comment by otetard** [comment]
PR here: #25
