### ISSUE TITLE
Enable ethercalc multisheets

### ISSUE THREAD

**Issue by hirunatan** [otetard/ownpad#26]
Ethercalc already have multi-sheet support:

https://github.com/audreyt/ethercalc/issues/138

If you prepend a '=' to the url of a spreadsheet (example change https://ethercalc.org/xactbt7sl4po to https://ethercalc.org/=xactbt7sl4po), it opens a document with multiple sheets, that you may access via tabs at the bottom of the screen.

It would be very good if this were added to ownpad, so users may create multisheet documents from Owncloud/Nextcloud.

**Comment by hirunatan** [comment]
:+1:

**Comment by kousu** [comment]
I just updated ethercalc on my server and couldn't figure out how to make multiworksheet spreadsheets. ethercalc.org also does not seem to have this enabled.

Has this not made it out to npm yet?
