### ISSUE TITLE
Support for Nextcloud12

### ISSUE THREAD

**Issue by muppeth** [otetard/ownpad#27]
Although bumping the `max-version` in `apps/ownpad/appinfo/info.xml` Enables the app, displaying .calc files results in white page. .pad files are working properly.

**Comment by otetard** [comment]
That’s strange. I’ve just checked compatibility with NC12: pads and calcs open correctly without any errors on my systems.

Do you have any error returned by PHP and/or in your browser console?

Olivier;

**Comment by muppeth** [comment]
Stupid me. Seems like I havent notice my ansible was not up to date and 
overwritten SAMEORIGIN header. That explains.
Sorry I bothered you.

**Comment by muppeth** [comment]
Seems like I was too quick to jump into conclusions. My production server (pointing to the same ethercalc instance) works, however it's most certain the problem is on my test server side and not necessary ownpad fault. 
If that turns to be false I will update you (sorry for re-opening, I need more coffee).
