### ISSUE TITLE
Multi-sheet doesn't work

### ISSUE THREAD

**Issue by imsearcher** [otetard/ownpad#28]
Hi,
Ownpad can not display the spreadsheets I created. I found InternetShortcut is correct. However, "=" is encoded to %3D in the viewer.php. Then ethercalc server is not able to recognize the name.
I use owncloud 9.

**Comment by otetard** [comment]
Hi!

Thanks for the feedback. I’ve just fixed two issues with Ethercalc support concerning URL checking (bb26f5ad2581cfef33f12c436d4b44eb88f3b375 and d8305d39b13cadfd157d0a050c1dfa6d8a3ca413) and prevent URL encoding of the first `=` if present in the URL (88d72ed80ccb81dcccc9b0d0546c66262aa5cd20).

Could you tell me if this solves your problem?

Olivier;

**Comment by imsearcher** [comment]
Hi Olivier,

It works perfectly. Thank you very much!

**Comment by kousu** [comment]
This is working for me too. I don't think @poVoq is right about this having anything to do with #45.
