### ISSUE TITLE
Ownpad breaking mimetypes for other files

### ISSUE THREAD

**Issue by muppeth** [otetard/ownpad#3]
I noticed that when enabling ownpad, mime types of other files aploaded via webui do not work. That is also the case with Documents app that will not recognize odt files and thus not initialize the editor.

**Comment by muppeth** [comment]
The dirty way around it is by following the owncloud documentation at: [https://doc.owncloud.org/server/9.1/admin_manual/configuration_mimetypes/index.html](url) I commented out two lines in your **app.php** and instead created **config/mimetypemapping.json** where i specified mimetypes for pad and calc. 

After that everything works just fine. Pads are being open in ownpad app and other files and Documents are working as well. 

I hope you will find a clever way to implement it in your code (or someone else will).

Btw. thanks for this app. It's a blessing for me and my project.

**Comment by otetard** [comment]
I’ve fixed the `app/app.app` and documented how to work around this issue in this commit: 2b324e050fd0862e7e08e34adc1341b44efeaed8, but this is far from being perfect…

Olivier;
