### ISSUE TITLE
Not working in public directory

### ISSUE THREAD

**Issue by Rudloff** [otetard/ownpad#30]
Hello,
I'm using ownpad 0.5.9 with Owncloud 9.1.5.
When a pad is in a publicly shared directory, clicking on it does not open the pad correctly.
Here is an example (`Test.pad`): https://drive.animafac.net/index.php/s/CPZEAyP8IOTNDkv
The same pad works correctly when logged in.

**Comment by mbrgm** [comment]
@otetard Could you maybe point me to the according locations in the source to implement this? I'd be really happy to have this feature and would be willing to add it.

**Comment by jeromeLB** [comment]
Ownpad is a great app but the sharing link to modify the pad is a real important feature
Have you plan to add this ?

**Comment by otetard** [comment]
I don’t currently plan to implement this feature, but if someone wants to do it, I’m prone to review and merge it.

I don’t know exactly what should be done to implement this feature, we could probably use the `files_pdfviewer` app as an example here.

**Comment by b3nks** [comment]
You can rename the file with extension *.url instead of *.pad to make it open in another Tab for users who have only access to the shared version.

**Comment by otetard** [comment]
I’ve started to work on that feature in a dedicated branch: [`public-viewer`](https://github.com/otetard/ownpad/tree/public-viewer).

Some use case still needs to be fixed (don’t allow to open private pad even if shared for instance), but it’s working.
