### ISSUE TITLE
Etherpad is not displayed in Nextcloud

### ISSUE THREAD

**Issue by c456fa2** [otetard/ownpad#38]
When I create a new pad and open it, Nextcloud displays an empty frame below the Nextcloud  headline.
When I open the file in a new tab it is offered to be downloaded.

I did the following steps:

1. clone into /apps
2. activated  ownpad in settings
3. set pad url to `localhost:9001` (the pad runs on the same machine as nc) 
4. set mime types
5. restart nginx and php7

The etherpad log doesn't show any access.

Did I miss any step?
Do you need more information?

**Comment by LeCoyote** [comment]
Same here. Short investigation reveals that the empty frame is, in fact, a simple iframe. So if you are not running the server locally, there is no chance to access `localhost` remotely. I guess it means the ethercalc instance has to be public, which isn't great privacy-wise.

**Comment by otetard** [comment]
Etherpad/Ethercalc instance has to be publicly accessible directly. Ownpad is not much more than a frontend to Etherpad/Ethercalc. If you want to have pads with limited access and use Nextcloud as a gatekeeper to your pads, you should try the [`feature/etherpad-api`](https://github.com/otetard/ownpad/tree/feature/etherpad-api) branch.

**Comment by LeCoyote** [comment]
Thanks for the feedback, will look into this.
