### ISSUE TITLE
Config instructions are not clear

### ISSUE THREAD

**Issue by stemy2** [otetard/ownpad#39]
Hello,

I'm using nextcloud on my own server and i don't undestand the config instruction.
1) I don't have any «Collaborative document» section, just one named «Collabora online». So i clicked on this and i filled it with an etherpad instance (etherpad.net for example). Now, when i try to open a document, i have an internal server error.

Could you make more clear/updated instructions ?

Thanks.

**Comment by spaetz** [comment]
Try admin->additional settings -> collborative documents. If that works for you, I bet a pull request with improved documentation is welcome :-). (P.S. I am not the author of ownpad)

**Comment by stemy2** [comment]
Did you read what i wrote ? I just said that i don't have anything called «collaborative documents» anywhere, including in the additional settings.

**Comment by spaetz** [comment]
Whoa, no need to start getting angry at me! I am just a volunteer. I was not sure you were looking in the advanced settings section, as you were not mentioning these in your report, so no I could not have read that part. Collabora online is something completely different and not related to etherpads.

**Comment by otetard** [comment]
Hi all and sorry for the late answer,

Thanks very much @spaetz for your help :).

@stemy2 Sorry but I don’t really understand your issue (and I’m don’t really appreciate the way you talk to people that tries to help, we don’t owe you anything). If you installed and enabled Ownpad on your Nextcloud installation, you should be able to see a “Collaborative documents” in the “Additional settings” section of your configuration panel.

What version of Nextcloud are you using? Did you install Ownpad through the app market?

Olivier;

**Comment by otetard** [comment]
@stemy2, could you check if you still have this issue with the latest version of Ownpad (not available yet in the appstore). Your issue might have been fixed by 5ffe1d134c5150479ddc9224a2c833fafe591ea7.

**Comment by otetard** [comment]
I close this issue since it wasn’t updated for a long time (and I have no confirmation that this bug is still valid). Feel free to reopen it!
