### ISSUE TITLE
Propagate user/ACL from ownCloud to Etherpad

### ISSUE THREAD

**Issue by otetard** [otetard/ownpad#4]
Original request: https://apps.owncloud.com/content/show.php?content=174679

Make ownpad use ownCloud’s API to authenticate and check user rights within Etherpad. This must be optional since this will then create private pads, and will require to use Etherpad API.

_Not sure if it’s possible to make use of such mechanism with Ethercalc._

**Comment by otetard** [comment]
I’ve started to work on that topic. A first preview is available in the [`feature/etherpad-api`](https://github.com/otetard/ownpad/tree/feature/etherpad-api) branch.

Olivier;

**Comment by inos-github** [comment]
Hi Olivier, thank's for working on that.
I didn't find a solution to use OC/NC for third party user authentication so I have opened an issue at: https://github.com/nextcloud/server/issues/716

Concerning EtherCalc: as far as I can see, there is a key based authentication system for read/write access only and no user based authentication.

**Comment by inos-github** [comment]
I have tried the app from the new branch but for me it does not work until now. 
My configuration as follows:
- The cloud has a sub-domain: cloud.my-domain.de
- The pad has a sub-domain: pad.my-domain.de with a proxy  (apache) redirecting to localhost:port
- Both sub-domains have SSL, the etherpad on localhost:port dos not
- in settings: 
  - Etherpad Host:  https://pad.my-domain.de
  - Etherpad cookie domain:  pad.my-domain.de (is this correct? I have tried .my-domain.de as well)

New pads are created but opening a pad (regular as well as protected)  results in `You do not have permission to access this pad` message.
There is nothing in the cloud log
The etherpad log stats: 
```
[2016-08-04 15:38:22.438] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"g.h7CTV92YKJuJCEJZ$PmwuY4kJ8sbEy9JE","sessionID":"null","password":null,"token":"t.mjDCWZyqrWef2xHEbOPV","protocolVersion":2}
```

**Comment by otetard** [comment]
Thanks for the feedback. 

For “Etherpad cookie domain” you should use `my-domain.de` (you can’t push cookies for another domain).

In your Etherpad log, the `sessionID` shouldn’t have the “null” value. Do you have the latest version of the `feature/etherpad-api` branch? In particular, commit 36fe634097ebb8e32086036007ca47dff353c39d is important.

Olivier;

**Comment by inos-github** [comment]
Thanks for your quick reply!
with the correct cookie domain setting I can now open both regular pads and protected pads from within the cloud. I can not open regular pads directly with the etherpad frondend or via the synchronized shortcut. The log output:
` Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"g.Le6jTsHVuruFhZRx$Se1JRYNbTkAobe9p","sessionID":"s.19e6b026bc8cffd55b8b0c0bbf94fc61","password":null,"token":"t.mjDCWZyqrWef2xHEbOPV","protocolVersion":2}`

Thanks so much for your awesome work! Unfortunately I have only very very basic programming skills, otherwise I could help... :-(

Martin

**Comment by inos-github** [comment]
Hi Olivier,

the current etherpad-api branche version (fe6dd30) causes a reloading-loop on the login page even prior logging in. There is nothing related in the logfile.
My cloud version: Nextcloud 9.0.53 (stable)

best regards
Martin

**Comment by otetard** [comment]
Concerning NextCloud compatibility, I’ve just opened a new bug: #6. I didn’t have time to check for NC compatibility (but I plan to fully support it ;)).

**Comment by blackisle51** [comment]
As a side request to this topic - would it be possible to auto-fill the current OC/NC user name to the "Show the users on this pad" field?

**Comment by otetard** [comment]
> As a side request to this topic - would it be possible to auto-fill the current OC/NC user name to the "Show the users on this pad" field?

It works this way in the [`feature/etherpad-api`](https://github.com/otetard/ownpad/tree/feature/etherpad-api) branch. Your username/display name is used on Etherpad.

Olivier;

**Comment by inos-github** [comment]
In my case, the session-timeout is too short so I added a option in admin-settings to edit the timeout value:

sorry, until now, I am not familiar with git so I will post the changes here...

in ./settings.php insert after line 23
` $template->assign('ownpad_sessionTimeout', $appConfig->getAppValue('ownpad', 'ownpad_sessionTimeout', '36000'));`

in ./templates/settings.php insert after line 45
`<label for="ownpad_sessionTimeout"><?php p($l->t('Session Timeout')); ?></label>`
`<input type="text" name="ownpad_sessionTimeout" id="ownpad_sessionTimeout" value="<?php p($_['ownpad_sessionTimeout']); ?>" />`

in ./controller/displaycontroller.php  insert after line 83
`$sessionTimeout = $this->config->getAppValue('ownpad', 'ownpad_sessionTimeout');`
and edit line 90 to
`$session = $this->eplInstance->createSession($groupID, $author->authorID, time() + $sessionTimeout);`

Martin

**Comment by poVoq** [comment]
Any progress on this?

This might help as a reference for the etherpad side of things:
https://github.com/michael-dev/dokuwikietherpadlite

**Comment by poVoq** [comment]
This might also be helpfull?:
https://github.com/kurounin/ep_auth_session

**Comment by otetard** [comment]
> Any progress on this?

I don’t have much time to work on this plugin, but this plugin is open for pull requests :).

As said previously, the [`feature/etherpad-api`](https://github.com/otetard/ownpad/tree/feature/etherpad-api) branch should work for basic use cases.

Olivier;

**Comment by poVoq** [comment]
> As said previously, the feature/etherpad-api branch should work for basic use cases.

That branch seems quite outdated otherwise, does it even support NC12?

**Comment by poVoq** [comment]
I tried installing the master branch but it gives me a "Error: This app can not be enabled because it makes the server unstable" when I try to enable it.

**Comment by otetard** [comment]
> I tried installing the master branch but it gives me a "Error: This app can not be enabled because it makes the server unstable" when I try to enable it.

Could you open a new issue explaining this bug please?

Olivier;
