### ISSUE TITLE
cant open etherpad, NC wants to download file

### ISSUE THREAD

**Issue by hajika** [otetard/ownpad#41]
What I have done yet: Installed the ownPad app. Then in admin/additional settings added the link to the etherpad and saved it.

But when I use the + to create a new pad, it will create a file. When I click that file, firefoc asks me to download it. Nothing happens like opening the pad or something like that.

Nextcloud 12, firefox on Xubuntu 16.04

**Comment by geislern** [comment]
Have you seen the remark about Mimetypes in the readme? I think this should fix exactly this (for files created after you edit the mimetypes.json acording to the instructions in the README).

**Comment by spaetz** [comment]
Hi there, I have copied the mimetype file added the 2 lines and rerun the occ file:scan but I still get a download offered, so in some cases this does not seen to be fixing the issue. Happy to help debug more in case it is needed.

**Comment by geislern** [comment]
Did you do this before creating a the file? If not try creating a new pad and opening that one.

**Comment by spaetz** [comment]
Yes, I restarted PHP and created a new pad afterwards and I still get a "pad file" offered for download.

**Comment by clumsycat** [comment]
same issue. 

- environment:

1. nextcloud docker ([wonderfall/nextcloud](https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud))

2. etherpad docker ([tvelocity/etherpad-lite](https://github.com/tvelocity/dockerfiles/tree/master/etherpad-lite))

- diff:

1.  don't have `mimetypemapping.json` file in` /config `. I just copy one from ([mimetypemapping.dist.json](https://github.com/nextcloud/server/blob/eab2b3b7aee7734c5c1253a1be3896e0ecf7947c/resources/config/mimetypemapping.dist.json))

**Comment by otetard** [comment]
It seems to me that you missed something in your configuration.

Here is a first list of checks you can do:
- is the file `config/mimetypemapping.json` exists (if not, copy it from `/resources/config/mimetypemapping.dist.json` and don’t forget to remove the `.dist` in its name)?
- is the file `config/mimetypemapping.json` contains the two entries for “`pad`” and “`calc`” (you can refer to the `README.md` file for more information)?
- did you asked `occ` to rescan all files (`sudo -u www-data php occ files:scan --all`)?
- do you encounter the same issue even with newly created pads?
- in your HTML content, what is the value of the `data-mime` attribute associated to a newly created pad ([you can see here where the to find this value](https://user-images.githubusercontent.com/2007634/33315301-9dc91720-d430-11e7-8f94-add56e7ff86b.png))

Olivier;

**Comment by clumsycat** [comment]
@otetard 
I've checked all the steps you listed. It didn't work.
And I got a wrong value `data-mime="application/octet-stream"`.
