### ISSUE TITLE
API based PAD creation only option doesn't work with Etherpad

### ISSUE THREAD

**Issue by poVoq** [otetard/ownpad#44]
I have configured my Etherpad with the following option:
`
/* Users may edit pads but not create new ones. Pad creation is only via the API. This applies both to group pads and regular pads. */
  "editOnly" : true,
`
Which seemed the right option to reduce public access and only allow pad creation from within Ownpad... however it seems ownpad isn't actually using the API?
At least for me it also shows the same "You do not have permission to access this pad" message in Ownpad as when trying to create a new pad directly.

**Comment by otetard** [comment]
In order to use Etherpad with its API, you should try the [`feature/etherpad-api`](https://github.com/otetard/ownpad/tree/feature/etherpad-api) branch. This is an unfinished work but it should work, at least for basic use cases.
