### ISSUE TITLE
Archiving

### ISSUE THREAD

**Issue by kousu** [otetard/ownpad#47]
Etherpad and Ethercalc both timeout their content when it's not touched for a while. This is too bad, because NextCloud's UI, and ownpad's place in it, suggests durability. I assume that ownpad is not notified by either app when a document times out? So then those .pad and .calc files will just sit there, silently useless, until someone goes looking for an old file?

Is there anything in the API of either app that lets you mark a document as non-deleteable?

Can ownpad query to tell us how long our documents will survive?

**Comment by otetard** [comment]
Ownpad is not really intended to be used with [beta.etherpad.org](http://beta.etherpad.org/) and/or [ethercalc.org](https://ethercalc.org/) but rather with your own instances of these software. Deletion policies are specific to the people that hosts EP/EC and relies on either local scripts or plugins ([example](https://groups.google.com/forum/#!topic/etherpad-lite-dev/hq-CQzP9TPg)).

AFAIK there is nothing in the API that can prevent from deleting pads or calcs…

Olivier;

**Comment by kousu** [comment]
You're right. I am 99% sure that the default ethercalc install keeps things forever, but it's not super clear to me; I know the default etherpad install deletes things after 30 days. It would be helpful if you had a note in the user documentation about how to check this.

 It would also help if the underlying apps had an API to support this, so I've opened those tickets over there.

**Comment by JohnMcLear** [comment]
"Etherpad ... timeout their content when it's not touched for a while. This is too bad, "  - It does?  What do you mean by timeout?  I am pretty sure this is incorrect.
