### ISSUE TITLE
Multi-sheet-support for ethercalc breaks ownpad-ethercalc

### ISSUE THREAD

**Issue by laryllian** [otetard/ownpad#66]
Dear otetard and crew, thanks so much for this helpful nc-app. I love it. :D

But here is my problem, maybe you can help: Multi-sheet-support for ethercalc breaks ownpad-ethercalc on my instance. Whenever I create a table with the "+" and choose "Calc", a table is created, but the intended "=" sign in the link becomes "%3D", such as in https://domain.org/calc/%3DKH79P35Vf...

Ethercalc however cannot process this "percentage-link" and in effect always shows the same table regardless of the actual link. My workaround is changing the file "lib/Service/OwnpadService.php" on line 40.

Old line (with multi-sheet-support ):
            $url = sprintf("%s/=%s", rtrim($host, "/"), $token);

New line (without multi-sheet-support):
            $url = sprintf("%s/%s", rtrim($host, "/"), $token);

Now the links work, but the tables naturally only have one sheet. Does anyone know, where this comes from and how I can tackle this to get multi-sheet-support? Thank you

My setup:
CentOS 7 with PHP 7.1.20
Nextcloud 13.0.4
Ethercalc 2010-07-05
Ownpad 0.6.8

**Comment by poVoq** [comment]
This seems to work fine with the newest version of Ethercalc available through dockerhub:
https://hub.docker.com/r/audreyt/ethercalc/

**Comment by otetard** [comment]
I’m closing this issue since this is a very old one. Please open a new issue if you still encounter this issue with the latest version of Ownpad!
