### ISSUE TITLE
Etherpad for Ownpad only

### ISSUE THREAD

**Issue by Dubidubiduu** [otetard/ownpad#72]
Now it works just fine, but for security reasons I want etherpad to work in ownpad only. Can you give me a hint how to do it? Maybe this could be part of documentation, since this could be a common issue?

Good work btw!

**Comment by otetard** [comment]
Information is available in the README.md file, in the “[Create access restricted pads](https://github.com/otetard/ownpad#create-access-restricted-pads)” section:

> If you want to create truly private pads, you have to dedicate an Etherpad instance for Nextcloud. You will then configure Etherpad to restrict pad access via sessions and pad creation via the API. For this, you have to adjust your Etherpad configuration file (settings.json) as following:
> ```
> "requireSession" : true,
> "editOnly" : true,
> ```

This means that your Etherpad instance won’t allow users to create pads directly. You’ll need to use the API to do so.

If I misunderstood your question, feel free to re-open that issue!
