### ISSUE TITLE
Unable to create public pad if Etherpad API is not used

### ISSUE THREAD

**Issue by jeyca** [otetard/ownpad#75]
Iam using NC 14.04 and ownpad 0.6.8. I managed to set up ownpad with mime settings and so on, but when I open my new created pad, it only shows me the NC header, a black bar that seems to come from ownpad (with file name and link to pad when I hover it) but below there only a white screen and nothing else. I even cant write in this screen. 

![screenshot_2018-12-07_13-20-52](https://user-images.githubusercontent.com/37297730/49647487-f4576380-fa22-11e8-8063-a0b59fb12fac.png)

And when I lookup the Network connections in Firefox developer, I see that there is no connection established (or even tried to establish) to the pad server, so its actually not possible that there is anything shown :) 

What is possibly going wrong here? Why is the pad not loaded?

**Comment by ezzra** [comment]
cant you say, what it should look like? Should this black bar be there?

**Comment by otetard** [comment]
This bug seems to have been introduced by 22ea59c92a5dddaf6717d856e6860dd258154e8b. Fix should be easy (we just need to add a check to be able to create pad if API is not allowed).

**Comment by jeyca** [comment]
@otetard can you explain what the actual problem is and how to fix it for my setup? Is it, because my padserver does not allow api access? I could actually change that as well

**Comment by otetard** [comment]
That is a regression introduced in [v0.6.9](https://github.com/otetard/ownpad/releases/tag/v0.6.9). You could either fix the issue (by analyzing 22ea59c92a5dddaf6717d856e6860dd258154e8b which introduced the bug) or rollback your version to 0.6.8.

I’ll try to find some time to fix the issue in a new version in the following days.

**Comment by otetard** [comment]
That issue should be fixed by 14666c00d758d2ed93f0dca514b87221ebe983eb. A new release will be pushed shortly to the Nextcloud appstore.
