### ISSUE TITLE
Etherpad could not be opened

### ISSUE THREAD

**Issue by MathiasRenner** [otetard/ownpad#79]
### Steps to reproduce:
1. Install Ownpad
1. In config, activate Etherpad and add "https://etherpad.wikimedia.org" als server URl
1. Create new Etherpad file and click on it. Error:  
**"Your Etherpad/Ethercalc document could not be opened: the URL specified in your file does not match the allowed server."**

### Environment:
NC v. 15.0.0
Installed latest Ownpad, and the mimetype fix

Any help?

**Comment by c7hm4r** [comment]
I got the same error when migrating a Nextcloud 14 and an Etherpad instance to another domain.

I needed to change the OwnPad settings in Nextcloud to the new domain name. Furthermore, I downloaded, edited and uploaded the pad files as the contain the domain name, too. Then the error disappeared.

**Comment by 42ske** [comment]
Any news on this?
