### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by tpape** [otetard/ownpad#80]
Hello,
I just deployed ownpad in my instance. Everything works well, but since my users are young students I would like to add the Etherpad-lite icon to the pad files on the list, is it possible to do it manually ? Is it possible to add this feature ? Or is it a bug from my instance ? 

Here is what it looks right now : 
![pad](https://user-images.githubusercontent.com/6071630/50838909-f07a7200-133d-11e9-8ad3-9a625a16f38b.png)

Many thanks !

Best regards,
Thomas

**Comment by otetard** [comment]
This feature was implemented in 3620bde4ab35629551c64630a8332b1d8a0319c6 (not yet released).
