### ISSUE TITLE
Owncloud 16 is stable now.

### ISSUE THREAD

**Issue by noci2012** [otetard/ownpad#88]
Can this be updated?

**Comment by otetard** [comment]
I’ve pushed a new release (0.6.13). A pull request, diff or any kind of help would have been appreciated for this simple task.

**Comment by noci2012** [comment]
It was entirely unclear what would be needed to upgrade. 
only a fix of the allowed version number or a complete rewrite of some module.
(I dont have multiple instances / versions of 'Nextcloud running... So as long as there are undecidable issues  i can't upgrade..) 
So sorry for not providing a pull request with unknown contents.
