### ISSUE TITLE
Recommendations app displayed along with Pad or Calc

### ISSUE THREAD

**Issue by sunjam** [otetard/ownpad#89]
The new recommendations app continues to be displayed when a pad or calc in opened in latest Nextcloud 16.0.3
![ownpad-recommendations](https://user-images.githubusercontent.com/1787238/62571586-92b3f700-b846-11e9-994f-7c4026ac02ea.png)

**Comment by otetard** [comment]
Is this issue still valid with the latest versions of Nextcloud?

**Comment by muppeth** [comment]
I'm having similar issue (currently on 17.0.1)
![Screenshot from 2020-01-27 17-11-49](https://user-images.githubusercontent.com/8480830/73191780-580d8600-4128-11ea-89e9-de24c351ed75.png)

**Comment by otetard** [comment]
This issue is now fixed in 0.8+ versions of Ownpad (as it now uses the Viewer app to display pad/calc content).
