### ISSUE TITLE
When will ownpad be compatible with Nextcloud V17 

### ISSUE THREAD

**Issue by noci2012** [otetard/ownpad#93]

**Comment by otetard** [comment]
Thank you for your contribution.

**Comment by LucN31** [comment]
On nextcloud 17, in some cases only the black banner is displayed and the file manager remains on the rest of the screen. It is not an etherpad problem : when using the direct link in the banner the pad is displayed an it can be edited outside nextcloud. I have not an ssh acces to debug, howto determine the problem ?
Thx,
Luc.

**Comment by brdelphus** [comment]
Any updates on this issue ? Your app is really important to my nextcloud usage and i quite regret updating to 17 now

**Comment by LucN31** [comment]
Hi,
Sorry for my absence.
**Owncloud is compatible with NextCloud 17.0.2, it works fine.**

We had 2 problems : 
1. Only black banner displayed
 due to PrivacyBadger lock :-\ 
1. Transparent background using framacalc and etherpad (only time slider)
solved with Nextcloud 17.0.2 upgrade.

Luc.

**Comment by brdelphus** [comment]
> Hi,
> Sorry for my absence.
> **Ownpad is compatible with NextCloud 17.0.2, it works fine.**
> 
> We had 2 problems :
> 
>     1. Only black banner displayed
>        due to PrivacyBadger lock :-\
> 
>     2. Transparent background using framacalc and etherpad (only time slider)
>        solved with Nextcloud 17.0.2 upgrade.
> 
> 
> Luc.

Oh I see, I was able to install it now, it said enabled, but i cant reach out its settings on settings, administration, additional settings. there nothing there related to ownpad on admin or any user

**Comment by brdelphus** [comment]
> Hi,
> Sorry for my absence.
> **Ownpad is compatible with NextCloud 17.0.2, it works fine.**
> 
> We had 2 problems :
> 
>     1. Only black banner displayed
>        due to PrivacyBadger lock :-\
> 
>     2. Transparent background using framacalc and etherpad (only time slider)
>        solved with Nextcloud 17.0.2 upgrade.
> 
> 
> Luc.

Indeed it works now, before i was unable to activate it now it just works, not sure if something was really updated, but it just works now. Thank you for your support

**Comment by otetard** [comment]
I’ve pushed a new Ownpad revision that is marked as compatible with Nextcloud 17 & 18. I’ve quickly checked that everything works fine. If you find any issue related to that Nextcloud versions, please open a new issue!

Sorry for not being enough reactive with this app. This app is open to contributions and pull requests ;).
